### ISSUE TITLE
The future of callingallpapers.com

### ISSUE THREAD

**Issue by heiglandreas** [joindin/callingallpapers.com#55]
Due to recent events I'd really like to clear the state of callingallpapers inside the joind.in project. That has nothing to do with hurt feelings or or misunderstandings. It just showed that I for myself and the joindin-team as well should define what part callingallpapers plays in the future. 

Yes, currently I am the only maintainer and the only other person with access to the API-server (that also runs the CLI) is Rob Allen (So when I'm hit by a bus, I tried to grant Rob full access to the DO stuff). But that does not need to stay that way. I came to the maintainership due to Lorna getting hold of the domain and asking me whether I'd be interested in maintaining it under the Joind.in Umbrella. 

The domain name was far to good to let it just sit there or give it up. the idea was to automatically aggregate all the different CfP-lists that were (and still are) around to make it easier for speakers to find relevant CfPs and to notify them before the CfP closes. Therefore in the long term becoming the main resource for CfPs not only in the PHP-community.As no one else volunteered to do it I stepped up and created the current setup. 

And since then the plattform languished. Every now and then I added a new Parser for a different CfP-System. There are not really metrics to esablish the reach of the API as that would have required more work to it which I never managed to put into it.

But so far I was under the impression that, if push comes to shove, the joind.in team is there for worst case scenarios. But from what I gathered so far that might not be the case now (which I can absolutely understand). So for me two main questions arose: 

* Is callingallpapers still a joind.in-Project or not? 
* And how can we/I find people to help out? 

So far I'Ve seen joind.in mainly as a project for speakers (we still need to discuss the target audience) and as such callingallpapers.com fitted into that perfectly. But if we decide that is not a perfect fit, then we need to take the necessary steps and exclude callingallpapers from the project-scope.

**Comment by svpernova09** [comment]
Speaking from the perspective of the Joindin Leadership team (which @heiglandreas is a member!) There is no problem at all having CAP under the joind.in umbrella. 

While The Joindin Foundation, Open Source Project, and Joind.in hosted service are my top priorities for the leadership team they don't have to be the only ones. My advice to you Andreas would be to document everything so that if the unfortunate would happen there would be a plan / place for someone to take over.

**Comment by svpernova09** [comment]
I didn't mean to close the issue, sorry about that!

**Comment by mattstauffer** [comment]
OK, so... y'all are officially back on board with supporting CAP and not just putting it on @heiglandreas' shoulders? I'm definitely getting some mixed messages, so I want to make sure it is 100% clear:

Am I correct to read that you all now consider CAP an official, supported, platform part of JoindIn, and there is no longer any internal confusion about its status?

Thanks!

**Comment by svpernova09** [comment]
@mattstauffer 

There was never any confusion from this side. Just some miscommunication it seems.

As long as there is a Joindin Project, Calling All Papers will be a welcome part of it.

**Comment by heiglandreas** [comment]
Short-Term goal is to provide documentation to eliminate bus factor. Mid-range goal is to find more shoulders to distribute the load onto. Until that is reached I plan to fully support the project and I'm happy to do that as part of the joind.in-family

**Comment by mattstauffer** [comment]
https://github.com/tightenco/symposium/pull/268#issuecomment-494406109

> here's little interest from the rest of the team to support it at this juncture. He can do whatever he wants with it as there isn't any official over site regarding the project. Moving your source of truth to an intermediary

"little interest from the rest of the team"
"isn't any official over site"
"an intermediary"

I'm not trying to be a jerk, but this is the the confusion I'm talking about. This is not the same message I'm seeing here, so I want to clarify.

Thanks!

**Comment by svpernova09** [comment]
> I'm not trying to be a jerk, but this is the the confusion I'm talking about. This is not the same message I'm seeing here, so I want to clarify.

I get it, I do, but at the same time I can only say "As long as there is a Joindin Project, Calling All Papers will be a welcome part of it." so many times before I just give up saying it.

**Comment by mattstauffer** [comment]
Maybe say "we had internal confusion that we've since cleared up" instead of "there was never any confusion" so it's not confusing to other people why we're getting conflicting messages from your "Primary Party" leadership?

If you say there wasn't confusion, but I'm looking at conflicting messages from y'all, then I feel like I am missing something.
If you say there *was* confusion and there isn't *any more,* then I feel like I'm not missing something and I can rest happy.

**Comment by svpernova09** [comment]
Before this issue, there was some undiscussed confusion around where CAP fit into Joindin among the Leadership Team which I blame on the fact we as a team hadn't gotten around to discussing it. I assumed we cleared up all of that discussion internally. Then @heiglandreas opened https://github.com/joindin/callingallpapers.com/issues/55 which I quickly responded to stating again that CAP was welcome in Joindin.

The leadership team discussed CAP in our Leadership Meeting from February 25th, 2019:

```
Calling all papers
Andreas gave some background. It’s being migrated to platform.sh and Andreas will move it across to the joind.in account so we share access and have continuity for that site as well as joind.in itself.
```

Paul commented in https://github.com/tightenco/symposium/pull/268#issuecomment-494406109 which did muddy the waters a bit:

```
@svpernova09 Can correct me if I say anything incorrect but CAP is @heiglandreas project, if he were to be hit by a bus tomorrow, there's little interest from the rest of the team to support it at this juncture. He can do whatever he wants with it as there isn't any official oversite regarding the project. Moving your source of truth to an intermediary is never advisable and could result in headaches down the road.
```

I didn't correct Paul because he's not wrong, most of the leadership team is focused on different areas of Joindin at the moment, not Calling All Papers. That doesn't mean CAP is going anywhere, it's just not where most of the leadership team is focusing their efforts. 

IMHO there is a distinct difference between "You're welcome here", and "You're not welcome here". No one has ever said (that I'm aware of) CAP was unwelcome in Joindin. I've stated several times the exact opposite.

Happy to chat in real time via voice if that would help clear things up.
